# -*- coding: utf-8 -*-
"""E-mail Marketing para Loja de Cosméticos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVGy2TQWeOunleJI_gvHGb3wxfugKcop
"""

import pandas as pd
import numpy as np
import random
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import matplotlib.pyplot as plt
import seaborn as sns


data = {
    'cliente_id': range(1, 101),
    'nome': [f'Cliente {i}' for i in range(1, 101)],
    'email': [f'cliente{i}@exemplo.com' for i in range(1, 101)],
    'preferencia': np.random.choice(['Maquiagem', 'Cuidado com a Pele', 'Perfume'], 100),
    'comportamento_compra': np.random.choice(['Alta', 'Média', 'Baixa'], 100)
}


clientes_df = pd.DataFrame(data)


print(clientes_df.head())


def gerar_email(nome, preferencia):
    assunto = "Novidades e Ofertas para Você!"
    corpo = f"""
    Olá {nome},

    Temos ótimas novidades na nossa loja de cosméticos que combinam com sua preferência por {preferencia}.

    Aproveite nossas promoções exclusivas!

    Atenciosamente,
    Sua Loja de Cosméticos
    """
    return assunto, corpo


segmentados = clientes_df[clientes_df['comportamento_compra'] == 'Alta']


def enviar_email(cliente):
    assunto, corpo = gerar_email(cliente['nome'], cliente['preferencia'])

    print(f"Enviando e-mail para: {cliente['email']}\nAssunto: {assunto}\n{corpo}\n")


for _, cliente in segmentados.iterrows():
    enviar_email(cliente)

taxa_conversao = 0.15
total_clientes_segmentados = len(segmentados)
conversoes = int(total_clientes_segmentados * taxa_conversao)

resultados = {
    'Total de Clientes Segmentados': total_clientes_segmentados,
    'Conversões': conversoes,
    'Taxa de Conversão (%)': taxa_conversao * 100
}

resultados_df = pd.DataFrame(resultados.items(), columns=['Métrica', 'Valor'])
sns.barplot(x='Métrica', y='Valor', data=resultados_df)
plt.title('Resultados da Campanha de E-mail Marketing')
plt.xticks(rotation=45)
plt.show()